
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (1, 'UKR', 'Ukraine');
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (2, 'RUS', 'Russia');
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (3, 'USA', 'United States');
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (4, 'SYR', 'Syria');
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (5, 'ARM', 'Armenia');
INSERT INTO COUNTRIES (ID, CODE, NAME) VALUES (6, 'AZE', 'Azerbaijan');


INSERT INTO CONFLICTS (ID, NAME, START_DATE, STATUS, DESCRIPTION)
VALUES (1, 'Russo-Ukrainian War', '2014-02-20', 'ACTIVE', 'Ongoing conflict between Russia and Ukraine.');

INSERT INTO CONFLICTS (ID, NAME, START_DATE, STATUS, DESCRIPTION)
VALUES (2, 'Syrian Civil War', '2011-03-15', 'ACTIVE', 'Multi-sided civil war in Syria involving several international actors.');

INSERT INTO CONFLICTS (ID, NAME, START_DATE, STATUS, DESCRIPTION)
VALUES (3, 'Nagorno-Karabakh Conflict', '1988-02-20', 'FROZEN', 'Territorial conflict between Armenia and Azerbaijan.');




INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (1, 1);
INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (1, 2);
INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (1, 3);


INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (2, 4);
INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (2, 3);
INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (2, 2);


INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (3, 5);
INSERT INTO CONFLICT_COUNTRIES (CONFLICT_ID, COUNTRY_ID) VALUES (3, 6);
